name: ccios_backend
description: CCIOS Video Scraper Backend
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  http: ^1.1.0
  html: ^0.15.4
  dio: ^5.4.0

dev_dependencies:
  lints: ^3.0.0
