name: ccios_player
description: Leisure影视 - 极简影视播放应用
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  video_player: ^2.8.2
  chewie: ^1.7.4
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
